language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install: 
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y catdoc"
  - "pip install coveralls"
  - "pip install pytest"
  - "pip install ."

# command to run tests
script: 
  - coverage run --source invoice `which py.test`

after_success:
  - coveralls --rcfile=tests/.coveragerc

# notifications:
notifications:
  email:
    recipients:
      - simone.campagna11@gmail.com
    on_success: change
    on_failure: always

# branches:
branches:
  only:
    - master
    - devel
    - multithreading
    - 
