language: python
python:
  - "3.2"
  - "3.3"

# command to install dependencies
install: 
  - "pip install coveralls"
  - "pip install pytest"
  - "apt-get install catdoc"
  - "pip install ."

# command to run tests
script: 
  - coverage run --source invoice `which py.test`

after_success:
  - coveralls --rcfile=tests/.coveragerc

# notifications:
notifications:
  email:
    recipients:
      - simone.campagna11@gmail.com
    on_success: change
    on_failure: always
